--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/Yunoxa/Pictures/Wallpapers/e32b041cf423642b7f172c51fadf6e476fb07c57f4bb0a2e8fc7274f33118d8b.png"

-- Special
background="#140907"
foreground="#f4ece5"
cursor="#f4ece5"

-- Colors
color0="#140907"
color1="#F7BFCE"
color2="#B0D7D6"
color3="#B3DDDC"
color4="#B3DDDC"
color5="#B9DFDE"
color6="#E0D5D3"
color7="#f4ece5"
color8="#aaa5a0"
color9="#F7BFCE"
color10="#B0D7D6"
color11="#B3DDDC"
color12="#B3DDDC"
color13="#B9DFDE"
color14="#E0D5D3"
color15="#f4ece5"
